# abyss
foreground            #6688cc
background            #000c18
selection_foreground  #ffffff
selection_background  #082050
cursor                #ddbb88
cursor_text_color     #000c18
url_color             #99ffff
active_border_color   #596f99
inactive_border_color #384887
active_tab_foreground   #000c18
active_tab_background   #6688cc
active_tab_font_style   bold
inactive_tab_foreground #6688cc
inactive_tab_background #10192c
tab_bar_background      #000c18
color0  #111111
color1  #ff9da4
color2  #d1f1a9
color3  #ffeead
color4  #bbdaff
color5  #ebbbff
color6  #99ffff
color7  #cccccc
color8  #333333
color9  #ff7882
color10 #b8f171
color11 #ffe580
color12 #80baff
color13 #d778ff
color14 #78ffff
color15 #ffffff
