# ayu-dark
foreground            #b3b1ad
background            #0a0e14
selection_foreground  #b3b1ad
selection_background  #273747
cursor                #e6b450
cursor_text_color     #0a0e14
url_color             #90e1c6
active_border_color   #53bdfa
inactive_border_color #686868
active_tab_foreground   #0a0e14
active_tab_background   #e6b450
active_tab_font_style   bold
inactive_tab_foreground #b3b1ad
inactive_tab_background #01060e
tab_bar_background      #0a0e14
color0  #01060e
color1  #ea6c73
color2  #91b362
color3  #f9af4f
color4  #53bdfa
color5  #fae994
color6  #90e1c6
color7  #c7c7c7
color8  #686868
color9  #f07178
color10 #c2d94c
color11 #ffb454
color12 #59c2ff
color13 #ffee99
color14 #95e6cb
color15 #ffffff
