# blackarch
foreground            #c9c9c9
background            #000000
selection_foreground  #000000
selection_background  #3a0000
cursor                #dd1111
cursor_text_color     #000000
url_color             #008787
active_border_color   #5f5faf
inactive_border_color #3a3a3a
active_tab_foreground   #000000
active_tab_background   #5f5faf
active_tab_font_style   bold
inactive_tab_foreground #c9c9c9
inactive_tab_background #101010
tab_bar_background      #000000
color0  #101010
color1  #c81e1e
color2  #5f8700
color3  #af8700
color4  #5f5faf
color5  #8b008b
color6  #008787
color7  #bcbcbc
color8  #3a3a3a
color9  #ff2222
color10 #87d700
color11 #ffd700
color12 #8787ff
color13 #d700d7
color14 #00d7d7
color15 #eeeeee
