# catppuccin-latte
foreground            #4c4f69
background            #eff1f5
selection_foreground  #4c4f69
selection_background  #ccd0da
cursor                #dc8a78
cursor_text_color     #eff1f5
url_color             #179299
active_border_color   #1e66f5
inactive_border_color #9ca0b0
active_tab_foreground   #eff1f5
active_tab_background   #1e66f5
active_tab_font_style   bold
inactive_tab_foreground #4c4f69
inactive_tab_background #dce0e8
tab_bar_background      #eff1f5
color0  #5c5f77
color1  #d20f39
color2  #40a02b
color3  #df8e1d
color4  #1e66f5
color5  #ea76cb
color6  #179299
color7  #acb0be
color8  #6c6f85
color9  #e64553
color10 #40a02b
color11 #fe640b
color12 #209fb5
color13 #8839ef
color14 #04a5e5
color15 #4c4f69
