# matrix
foreground            #00ff41
background            #000000
selection_foreground  #000000
selection_background  #0f3d0f
cursor                #00ff41
cursor_text_color     #000000
url_color             #00ffaa
active_border_color   #005f00
inactive_border_color #003b00
active_tab_foreground   #000000
active_tab_background   #005f00
active_tab_font_style   bold
inactive_tab_foreground #00ff41
inactive_tab_background #0a0a0a
tab_bar_background      #000000
color0  #0a0a0a
color1  #008f11
color2  #00ff41
color3  #39ff14
color4  #005f00
color5  #00d000
color6  #00ffaa
color7  #00cc33
color8  #003b00
color9  #00c020
color10 #5cff5c
color11 #7bff7b
color12 #008000
color13 #00e090
color14 #66ffcc
color15 #c8ffc8
