# monokai-dimmed
foreground            #c5c8c6
background            #1e1e1e
selection_foreground  #f8f8f2
selection_background  #676b71
cursor                #c07020
cursor_text_color     #1e1e1e
url_color             #66d9ef
active_border_color   #819aff
inactive_border_color #666666
active_tab_foreground   #1e1e1e
active_tab_background   #819aff
active_tab_font_style   bold
inactive_tab_foreground #c5c8c6
inactive_tab_background #282828
tab_bar_background      #1e1e1e
color0  #1e1e1e
color1  #c4265e
color2  #86b42b
color3  #b3b42b
color4  #6a7ec8
color5  #8c6bc8
color6  #56adbc
color7  #e3e3dd
color8  #666666
color9  #f92672
color10 #a6e22e
color11 #e2e22e
color12 #819aff
color13 #ae81ff
color14 #66d9ef
color15 #f8f8f2
