# terminal-red
foreground            #d6d6d6
background            #0a0a0a
selection_foreground  #0a0a0a
selection_background  #5a0000
cursor                #ff2b2b
cursor_text_color     #0a0a0a
url_color             #a05050
active_border_color   #8b0000
inactive_border_color #4d4d4d
active_tab_foreground   #0a0a0a
active_tab_background   #8b0000
active_tab_font_style   bold
inactive_tab_foreground #d6d6d6
inactive_tab_background #141414
tab_bar_background      #0a0a0a
color0  #141414
color1  #e60000
color2  #00a86b
color3  #d79921
color4  #8b0000
color5  #b03060
color6  #a05050
color7  #c0c0c0
color8  #4d4d4d
color9  #ff3b30
color10 #3ddc84
color11 #ffcf40
color12 #cc2200
color13 #e0607f
color14 #d08080
color15 #ffffff
