# tomorrow-night-blue
foreground            #ffffff
background            #002451
selection_foreground  #ffffff
selection_background  #003f8e
cursor                #ffffff
cursor_text_color     #002451
url_color             #99ffff
active_border_color   #bbdaff
inactive_border_color #404f7d
active_tab_foreground   #001733
active_tab_background   #bbdaff
active_tab_font_style   bold
inactive_tab_foreground #ffffff
inactive_tab_background #001c40
tab_bar_background      #001733
color0  #111111
color1  #ff9da4
color2  #d1f1a9
color3  #ffeead
color4  #bbdaff
color5  #ebbbff
color6  #99ffff
color7  #cccccc
color8  #333333
color9  #ff7882
color10 #b8f171
color11 #ffe580
color12 #80baff
color13 #d778ff
color14 #78ffff
color15 #ffffff
